  #page( main )    Version 1.09    9-25-21
from collections import OrderedDict
import text_display, world
from init import Player

#create dict of available user actions as key:value pairs i.e., n : move_north()
def action_adder(action_dict, hotkey, action, name_):
    action_dict[hotkey.lower()] = action
    action_dict[hotkey.upper()] = action
    print("{}: {}".format(hotkey, name_)) 

def get_available_actions(room_, player_):
    actions = OrderedDict()
    print("Choose an action:\n ")
    if player_.inventory:
        action_adder(actions, 'i', player.print_inventory, "Print inventory")
    #main: room_ = world.tile_at(player.x, player.y), is room_ of type Start
    if isinstance( room_, world.Start ):pass
    if isinstance( room_, world.EnemyTile ) and room.enemy.is_alive() :
        action_adder( actions, 'a', player.attack, "Attack" )
    if isinstance( room_, world.TraderTile ) and player.trade():
        action_adder( actions, 't', player.trade, "Trade" )
    else:
        if world.tile_at(room_.x, room_.y - 1): 
            action_adder(actions, 'n', player.move_north, "Go north")
        if world.tile_at(room_.x, room_.y + 1):
            action_adder(actions, 's', player.move_south, "Go south")
        if world.tile_at(room_.x + 1, room_.y):
            action_adder(actions, 'e', player.move_east, "Go east")
        if world.tile_at(room_.x - 1, room_.y):
            action_adder(actions, 'w', player.move_west, "Go west")
    return actions

#Gets users available actions list for each room
#populates/prints dict data, generated by action_adder()
def choose_action( _room, player_ ):
    action = None
    while not action:
        available_actions = get_available_actions( _room, player_ )
        action_input = input("\nAction: ")
        action = available_actions.get(action_input)
        if action: action()
        else: print("Invalid action!")

text_display.IntroScreen.intro_text()
world.parse_world_dsl()
 
player = Player()

#game loop
while player.is_alive():
    room = world.tile_at( player.x, player.y )
    text_display.IntroScreen.clear()
    text_display.IntroScreen.title_text()
    player.hud()
    print(room.intro_text())
    room.modify_player( player )
    
    if player.is_alive():
        choose_action( room, player )
    elif not player.is_alive():
        print("Your journey has come to an early end!") 
